### PR TITLE
Add Dark Mode

### PR DESCRIPTION
**Pull request by iqbalutomo**
I have implemented the dark mode feature in the app, hope this helps. #22

### CODE REVIEW

**Comment by johnbabu021** [comment]
Ok but we have a problem 
Change white background color including loading skeleton
To white

**Comment by iqbalutomo** [comment]
sorry can you explain which part is meant by loading skeleton?

**Comment by iqbalutomo** [comment]
i will fix it, but can you tell me in which component or on what page?

**Comment by johnbabu021** [comment]
Sidebar selector
Quantity selector 
Some more in product details page

**Comment by johnbabu021** [comment]
Screenshot_2021-10-05-14-14-43-779_com android chrome

**Comment by iqbalutomo** [comment]
Ok, do you mean i have to fix the sidebar button background color? and also the input background color becomes transparent?

**Comment by iqbalutomo** [comment]
Ok i try to fix it soon

**Comment by johnbabu021** [comment]
Yes

**Pull request merged**
