### PR TITLE
Custom Scrollbar

### LINKED ISSUE #15: create a custom scroll bar
scroll bar must be same width in the custom one 
color should be rgb(109, 40, 217)
background-color:white

### PR DESCRIPTION
**Pull request by KarishmaVanwari**
Custom scrollbar added as specified.
Fixed #15

### CODE REVIEW

**Comment by johnbabu021** [comment]
Hey I didn't find the scrollbar in the page @KarishmaVanwari

**Comment by KarishmaVanwari** [comment]
@johnbabu021 you can see the scrollbar when you click any of the images on the home page. Also, to see it on the home page, you can view it on a smaller screen size (mobile view).
Since the home page doesn't need scrollbar, it is not visible.

**Comment by KarishmaVanwari** [comment]
@johnbab you can see in the preview, the scrollbar is present.
sc-ss

**Comment by johnbabu021** [comment]
Screenshot_2021-10-05-15-09-36-850_com android chrome

**Comment by KarishmaVanwari** [comment]
@johnbabu021 in mobile, default scrollbar of mobile is used.
You can check on website and for mobile view check on desktop only.
Have a look at the preview.

**Pull request merged**
